const bodyParser = require('body-parser')
const express = require('express')
const dbConnect = require('./config/dbConnect')
const { notFound, errorHandler } = require('./middleware/errorHandler')
const authRoute = require('./routes/authRoute')
const productRouter = require('./routes/productRoute')
const blogRoute = require('./routes/blogRoute')
const categoryRoute = require('./routes/categoryRoute')
const brandRoute = require('./routes/brandRoute')
const couponRoute = require('./routes/couponRoute')
const app = express()
const dotenv = require('dotenv').config()
const PORT = process.env.PORT || 4000
const cookieParser = require('cookie-parser')
const morgan = require('morgan')
const slugify = require('slugify')
dbConnect()

app.use(morgan('dev'))
app.use(bodyParser.json())
app.use(bodyParser.urlencoded({extended:false}))
app.use(cookieParser())

app.use('/api/user', authRoute)
app.use('/api/product', productRouter)
app.use('/api/blog', blogRoute)
app.use('/api/cat', categoryRoute)
app.use('/api/brand', brandRoute)
app.use('/api/coupon', couponRoute)


app.use(notFound)
app.use(errorHandler)
app.listen(PORT, ()=>{
    console.log(`Server is running at PORT ${PORT}`)
})